use_frameworks!

platform :ios, '9.0'

target 'TRULoging_Example' do
  pod 'TRULoging', :path => '../'
  
  pod 'TRUNeteorking', :path => '../../TRUNeteorking'
  
  target 'TRULoging_Tests' do
    inherit! :search_paths

    
  end
end
